"""
Phase 22 — Centralized Alerting & Compliance Audit Trail Domain Schemas

Strongly-typed domain models for the alerting engine, compliance audit trail,
and safety verification snapshots. All models are pure data containers with
zero execution authority.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ── Alert Severity ────────────────────────────────────────────────────────────

class AlertSeverity(str, Enum):
    """Severity tier for operational alerts, ordered by escalation priority."""
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"


# ── Alert Category ────────────────────────────────────────────────────────────

class AlertCategory(str, Enum):
    """Functional category classifying the alert's operational domain."""
    SAFETY = "SAFETY"
    RISK = "RISK"
    EXECUTION = "EXECUTION"
    DATA_QUALITY = "DATA_QUALITY"
    SYSTEM_HEALTH = "SYSTEM_HEALTH"
    CALIBRATION = "CALIBRATION"
    COMPLIANCE = "COMPLIANCE"
    PROVIDER = "PROVIDER"
    RECONCILIATION = "RECONCILIATION"
    PERFORMANCE = "PERFORMANCE"


# ── Alert State ───────────────────────────────────────────────────────────────

class AlertState(str, Enum):
    """Lifecycle state of an individual alert."""
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"
    EXPIRED = "EXPIRED"


# ── Audit Action ──────────────────────────────────────────────────────────────

class AuditAction(str, Enum):
    """Categorized action recorded in the compliance audit trail."""
    ALERT_RAISED = "ALERT_RAISED"
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    ALERT_SUPPRESSED = "ALERT_SUPPRESSED"
    ALERT_ESCALATED = "ALERT_ESCALATED"
    RULE_TRIGGERED = "RULE_TRIGGERED"
    RULE_SUPPRESSED_DUPLICATE = "RULE_SUPPRESSED_DUPLICATE"
    SAFETY_CHECK_PASSED = "SAFETY_CHECK_PASSED"
    SAFETY_CHECK_FAILED = "SAFETY_CHECK_FAILED"
    COMPLIANCE_SNAPSHOT = "COMPLIANCE_SNAPSHOT"


# ── Alert Rule ────────────────────────────────────────────────────────────────

class AlertRule(BaseModel):
    """
    Configurable alert rule definition.

    Each rule defines a named condition with severity, throttle window,
    and optional escalation policy. Rules are evaluated periodically
    by the AlertingEngine.
    """
    rule_id: str = Field(..., description="Unique rule identifier")
    name: str = Field(..., description="Human-readable rule name")
    category: AlertCategory = Field(..., description="Functional category")
    severity: AlertSeverity = Field(..., description="Base severity when triggered")
    condition_description: str = Field(
        ..., description="Human-readable description of the triggering condition"
    )
    throttle_seconds: float = Field(
        default=300.0,
        ge=0.0,
        description="Minimum seconds between repeated alerts for the same dedup_key"
    )
    escalation_after_seconds: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Seconds after which an unacknowledged alert escalates severity"
    )
    escalation_severity: Optional[AlertSeverity] = Field(
        default=None,
        description="Target severity upon escalation"
    )
    enabled: bool = Field(default=True, description="Whether the rule is active")


# ── Alert ─────────────────────────────────────────────────────────────────────

class Alert(BaseModel):
    """
    Structured alert instance generated by the alerting engine.

    Each alert tracks its full lifecycle from creation through
    acknowledgement to resolution, including escalation metadata.
    """
    alert_id: str = Field(..., description="Unique alert identifier")
    rule_id: str = Field(..., description="Source rule that generated this alert")
    severity: AlertSeverity = Field(..., description="Current effective severity")
    category: AlertCategory = Field(..., description="Functional category")
    state: AlertState = Field(default=AlertState.ACTIVE, description="Lifecycle state")
    title: str = Field(..., description="Short alert title")
    message: str = Field(..., description="Detailed alert message")
    source_component: str = Field(
        default="", description="Originating subsystem or component"
    )
    metric_value: Optional[str] = Field(
        default=None, description="Observed metric value that triggered the alert"
    )
    threshold_value: Optional[str] = Field(
        default=None, description="Threshold that was exceeded"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the alert was created"
    )
    acknowledged_at: Optional[datetime] = Field(
        default=None, description="UTC timestamp when acknowledged"
    )
    resolved_at: Optional[datetime] = Field(
        default=None, description="UTC timestamp when resolved"
    )
    escalated: bool = Field(default=False, description="Whether the alert has been escalated")
    original_severity: Optional[AlertSeverity] = Field(
        default=None, description="Original severity before escalation"
    )
    dedup_key: str = Field(
        default="", description="Deduplication key for throttling identical alerts"
    )
    suppressed_count: int = Field(
        default=0, description="Number of duplicate alerts suppressed for this dedup_key"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional structured metadata"
    )


# ── Audit Entry ───────────────────────────────────────────────────────────────

class AuditEntry(BaseModel):
    """
    Immutable audit trail record.

    Once created, audit entries are never modified. They provide a
    chronological, append-only compliance log of all alerting and
    safety verification events.
    """
    entry_id: str = Field(..., description="Unique entry identifier")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the audit event"
    )
    action: AuditAction = Field(..., description="Categorized audit action")
    category: AlertCategory = Field(..., description="Functional category")
    severity: AlertSeverity = Field(..., description="Severity at time of recording")
    component: str = Field(default="", description="Source component or subsystem")
    description: str = Field(..., description="Human-readable description of the event")
    alert_id: Optional[str] = Field(
        default=None, description="Related alert ID, if applicable"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional structured metadata"
    )
    safety_verified: bool = Field(
        default=False,
        description="Whether this entry involves a safety invariant verification"
    )


# ── Alert Engine Status ──────────────────────────────────────────────────────

class AlertEngineStatus(BaseModel):
    """
    Summary status of the centralized alerting engine.
    """
    total_active_alerts: int = Field(default=0, description="Count of ACTIVE alerts")
    alerts_by_severity: Dict[str, int] = Field(
        default_factory=dict, description="Active alert counts grouped by severity"
    )
    alerts_by_category: Dict[str, int] = Field(
        default_factory=dict, description="Active alert counts grouped by category"
    )
    total_alerts_raised: int = Field(
        default=0, description="Total alerts raised since engine start"
    )
    total_suppressed: int = Field(
        default=0, description="Total duplicate alerts suppressed"
    )
    total_escalated: int = Field(
        default=0, description="Total alerts that were escalated"
    )
    total_audit_entries: int = Field(
        default=0, description="Total entries in the compliance audit trail"
    )
    rules_enabled: int = Field(default=0, description="Count of enabled rules")
    rules_disabled: int = Field(default=0, description="Count of disabled rules")
    engine_uptime_seconds: float = Field(
        default=0.0, description="Seconds since engine initialization"
    )
    last_evaluation_at: Optional[datetime] = Field(
        default=None, description="UTC timestamp of last rule evaluation cycle"
    )


# ── Compliance Snapshot ──────────────────────────────────────────────────────

class ComplianceSnapshot(BaseModel):
    """
    Point-in-time compliance verification snapshot.

    Captures the current state of all safety invariants and governance
    controls to demonstrate regulatory and operational compliance.
    """
    snapshot_id: str = Field(..., description="Unique snapshot identifier")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the snapshot"
    )
    live_trading_blocked: bool = Field(
        ..., description="Whether TIER_4_LIVE_REAL_MONEY is blocked"
    )
    execution_guard_active: bool = Field(
        ..., description="Whether ExecutionGuard is enforcing rules"
    )
    risk_engine_active: bool = Field(
        ..., description="Whether RiskEngine is enforcing constraints"
    )
    preflight_active: bool = Field(
        ..., description="Whether PreFlight gatekeeper is active"
    )
    kill_switch_armed: bool = Field(
        ..., description="Whether the operator kill switch is in ARMED (ready) state"
    )
    kill_switch_triggered: bool = Field(
        default=False,
        description="Whether the operator kill switch is currently triggered"
    )
    paper_broker_operational: bool = Field(
        ..., description="Whether PaperBrokerAdapter is functional"
    )
    safety_checks: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Individual safety check results"
    )
    overall_compliant: bool = Field(
        ..., description="Whether all safety invariants are satisfied"
    )


# ── Compliance Report ────────────────────────────────────────────────────────

class ComplianceReport(BaseModel):
    """
    Aggregated compliance report summarizing audit trail analysis.
    """
    report_id: str = Field(..., description="Unique report identifier")
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of report generation"
    )
    total_entries: int = Field(default=0, description="Total audit entries analyzed")
    entries_by_action: Dict[str, int] = Field(
        default_factory=dict, description="Entry counts grouped by action type"
    )
    entries_by_category: Dict[str, int] = Field(
        default_factory=dict, description="Entry counts grouped by category"
    )
    safety_checks_passed: int = Field(
        default=0, description="Total safety verifications that passed"
    )
    safety_checks_failed: int = Field(
        default=0, description="Total safety verifications that failed"
    )
    compliance_snapshots_count: int = Field(
        default=0, description="Total compliance snapshots recorded"
    )
    alerts_raised: int = Field(default=0, description="Total alerts raised")
    alerts_resolved: int = Field(default=0, description="Total alerts resolved")
    alerts_escalated: int = Field(default=0, description="Total alerts escalated")
    overall_compliance_rate: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Fraction of safety checks that passed (0.0 to 1.0)"
    )
    summary_message: str = Field(
        default="", description="Human-readable compliance summary"
    )


# Module version
ALERT_AUDIT_SCHEMA_VERSION = "22.0.0"
